/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dede_rust_jni_RustJNI */

#ifndef _Included_com_dede_rust_jni_RustJNI
#define _Included_com_dede_rust_jni_RustJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dede_rust_jni_RustJNI
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_rust_jni_RustJNI_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dede_rust_jni_RustJNI
 * Method:    md5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_rust_jni_RustJNI_md5
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dede_rust_jni_RustJNI
 * Method:    log
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dede_rust_jni_RustJNI_log
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
